[[permission]]
identifier = "file-read-write"
description = """This enables all file read and write related
commands without any pre-configured accessible paths."""
commands.allow = [
    "read_file",
    "read",
    "open",
    "read_text_file",
    "read_text_file_lines",
    "read_text_file_lines_next",
    "fs:read-files",
    "fs:scope-home",
    "fs:allow-mkdir"
]

[[scope.allow]]
path = "$HOME/*"
