# version: '3.8'

# windows用
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    # コンテナを起動したままにする
    tty: true
    # command: /bin/sh -c "yarn install && apt install -y libwebkit2gtk-4.1-dev  && yarn tauri dev"
    # command: /bin/sh -c "yarn install  && yarn dev"
    command: /bin/sh -c "yarn install  && yarn tauri dev"
    # command: /bin/sh -c "yarn install  && yarn tauri android init && yarn tauri android build"
    # command: /bin/sh -c "export PATH=/root/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"

    # android
    # command: /bin/sh -c "rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android && yarn install && yarn tauri android init && yarn tauri android build"

    environment:
      # Android
      - ANDROID_HOME=/root/Android/SDK
      - NDK_HOME=/root/Android/SDK/ndk/25.2.9519653
      # - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      # - PATH="/root/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"

      # ホストのディスプレイ設定をコンテナに渡す
      # windows
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      # XDGランタイムディレクトリを設定
      - XDG_RUNTIME_DIR=/tmp
      # PulseAudioサーバーの設定を渡す
      - PULSE_SERVER=$PULSE_SERVER

      # mac
      # - DISPLAY=host.docker.internal:0
      
      - LANG=ja_JP.UTF-8 
      - LC_ALL=ja_JP.UTF-8
      # - LIBGL_ALWAYS_SOFTWARE=1  # ソフトウェアレンダリングを強制
    volumes:
      - ./sqlite:/app
      - $HOME/Android/SDK:/root/Android/SDK
      # - /usr/lib/jvm/java-21-openjdk-amd64:/usr/lib/jvm/java-21-openjdk-amd64
      # X11ソケットをマウント（X11でのGUI表示用）
      - type: bind
        # windows
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        # mac
        # source: $HOME/.Xauthority  # X11認証情報のマウント
        # target: /root/.Xauthority  # コンテナ内での位置
    # ports:
      # - "1420:1420"
      # - "3000:3000"
      # - "8080:8080"
      # windows Waylandソケットをマウント（Waylandでのディスプレイ用）
      # - type: bind
      #   source: "${XDG_RUNTIME_DIR}/wayland-0"
      #   target: /tmp/wayland-0

# windows用ここまで

# mac用
# services:
#   app:
#     build:
#       dockerfile: Dockerfile
#       context: .
#     # コンテナを起動したままにする
#     tty: true
#     # command: /bin/sh -c "yarn install && apt install -y libwebkit2gtk-4.1-dev  && yarn tauri dev"
#     # command: /bin/sh -c "yarn install  && yarn dev"
#     command: /bin/sh -c "yarn install  && yarn tauri dev"
#     # command: /bin/sh -c "yarn install  && yarn tauri android init && yarn tauri android build"
#     # command: /bin/sh -c "export PATH=/root/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"

#     # android
#     # command: /bin/sh -c "rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android && yarn install && yarn tauri android init && yarn tauri android build"

#     environment:
#       # Android
#       - ANDROID_HOME=/root/Android/SDK
#       - NDK_HOME=/root/Android/SDK/ndk/25.2.9519653
#       # - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
#       - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
#       # - PATH="/root/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"

#       # ホストのディスプレイ設定をコンテナに渡す
#       # windows
#       # - DISPLAY=$DISPLAY
#       # - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
#       # XDGランタイムディレクトリを設定
#       # - XDG_RUNTIME_DIR=/tmp
#       # PulseAudioサーバーの設定を渡す
#       # - PULSE_SERVER=$PULSE_SERVER

#       # mac
#       - DISPLAY=host.docker.internal:0
      
#       - LANG=ja_JP.UTF-8 
#       - LC_ALL=ja_JP.UTF-8
#       - LIBGL_ALWAYS_SOFTWARE=1  # ソフトウェアレンダリングを強制
#     volumes:
#       - ./sqlite:/app
#       # - $HOME/Android/SDK:/root/Android/SDK
#       # - /usr/lib/jvm/java-21-openjdk-amd64:/usr/lib/jvm/java-21-openjdk-amd64
#       # X11ソケットをマウント（X11でのGUI表示用）
#       - type: bind
#         # windows
#         # source: /tmp/.X11-unix
#         # target: /tmp/.X11-unix
#         # mac
#         source: $HOME/.Xauthority  # X11認証情報のマウント
#         target: /root/.Xauthority  # コンテナ内での位置
#     # ports:
#       # - "1420:1420"
#       # - "3000:3000"
#       # - "8080:8080"
#       # windows Waylandソケットをマウント（Waylandでのディスプレイ用）
#       # - type: bind
#       #   source: "${XDG_RUNTIME_DIR}/wayland-0"
#       #   target: /tmp/wayland-0

# mac用ここまで


volumes:
  node_modules:
